apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-service
        image: online-store/checkout-service:dev
        env:
        - name: RABBIT_URL
          value: "amqp://guest:guest@rabbitmq:5672/%2F"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  selector:
    app: checkout-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
