apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-history
  template:
    metadata:
      labels:
        app: order-history
    spec:
      containers:
      - name: order-history
        image: online-store/order-history:dev
        env:
        - name: RABBIT_URL
          value: "amqp://guest:guest@rabbitmq:5672/%2F"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-history
spec:
  selector:
    app: order-history
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
